### ISSUE TITLE
调整后端服务从Python Tornado 调整至 Quarkus

### ISSUE THREAD

**Issue by Jansora** [Jansora/OnlineCompiler#10]
as title

**Comment by Jansora** [comment]
已解决

**Comment by aircjm** [comment]
docker部署完成之后 访问缺少js文件
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/18283183/202394460-41d80807-7c6c-41fa-8962-e03cb14d2a5d.png">

**Comment by Jansora** [comment]
> docker部署完成之后 访问缺少js文件 <img alt="image" width="1178" src="https://user-images.githubusercontent.com/18283183/202394460-41d80807-7c6c-41fa-8962-e03cb14d2a5d.png">

旧镜像删除了, 重新拉一下
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/28590000/202944345-ab9f106a-69b4-4d09-8d63-b744e959bbfe.png">

我 17号推上去后也发现了这个问题, 有重新推了一下

**Comment by aircjm** [comment]
> 

好的 我今天再试一下
